# Site Information
license:          "MIT"
license-url:      "https://github.com/blairanderson/tachyonstemplates/blob/master/LICENSE"
author:           "Tachyons Templates"
title: Free Tachyons Themes and Templates
google-analytics: "UA-61052500-15"
google_site_verification: false
bing_site_verification: "0C81C6A5BD3BAF86F4730D8C4A9BF223"
# Site Settings
baseurl:          ""
# Build settings
exclude:          [
  node_modules,
  sass-cache,
  _data,
  _components,
]
whitelist:
  - jekyll-redirect-from
# Dependencies
markdown:         kramdown
highlighter:      rouge
# Permalinks
permalink:        pretty
# Server
url:              http://www.tachyonstemplates.com
enforce_ssl:      false
encoding:         UTF-8
host:             127.0.0.1/
port:             9001

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - rouge

# Collections
collections:
  templates:
    output: true
    permalink: /template-overviews/:title/
  template-categories:
    output: true
    permalink: /template-categories/:title/

# Pagination
paginate: 5
paginate_path: "/articles/page:num/"
